name: 'build-test'
on:
  pull_request:
    branches: [main]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaharaJr/merge-pr@0.0.2
        id: pull_request_author
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
