name: 'build-test'
on:
  push:
    branches:
      - develop

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v4
        id: pull_request_author
        with:
          token: ${{secrets.TOKEN}}
          base: main