name: 'build-test'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: develop

      #  push changes to develop
      - name: set global attributes
        run: |
          git config --global user.email "bmsteve96@gmail.com"
          git config --global user.name "Benedict Steven"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
      - uses: ./
        id: pull_request_author
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Get the username
        run: echo "The author was ${{ steps.pull_request_author.outputs.author }}"
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'package.json'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.TOKEN }}
      # - name: update develop branch
      #   run: |
      #     git add package.json
      #     git add changelog.md
      #     git add action
      #     git commit -m "Skip CI"
      #     git push
