name: 'build-test'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: pull_request_author
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Get the username
        run: echo "The author was ${{ steps.pull_request_author.outputs.author }}"
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'package.json'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.TOKEN }}
          branch-name: develop
