name: 'build-test'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: pull_request_author
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Get the username
        run: echo "The author was ${{ steps.pull_request_author.outputs.author }}"
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: "1.1.1"
          release-notes: "* commits"

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: develop
          commit_message: Skip CI
          file_pattern: CHANGELOG.md
